drop table if exists books CASCADE;

drop table if exists electronic_books CASCADE;

create table books
(
    id                 bigint generated by default as identity,
    author             varchar(255) not null,
    genre              varchar(255) not null,
    number_of_pages    integer      not null,
    year_of_publishing varchar(255) not null,
    book_name          varchar(255) not null,
    primary key (id)
);

create table electronic_books
(
    id                   bigint generated by default as identity,
    author               varchar(255) not null,
    genre                varchar(255) not null,
    number_of_pages      integer      not null,
    year_of_publishing   varchar(255) not null,
    dimension            varchar(255) not null,
    electronic_book_name varchar(255) not null,
    text_format          varchar(255) not null,
    primary key (id)
);
